#!/bin/bash

export GITHUB_USER=""
export GITHUB_EMAIL=""
export device=""
export ROM=""
export ROM_DIR=""
export ROM_VERSION=""
export rom_vendor_name=""
export bacon="bacon"
export buildtype=""
export clean=""
export ccache=""
export ccache_size=""
export jenkins="true"
export release_repo=""
export timezone="UTC"
export tag=""
